kind: Namespace
apiVersion: v1
metadata:
  name: kerbal

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: kerbal
  name: openmct
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: openmct
    spec:
      containers:
        - name: openmct
          image: registry.mytools.live/openmct:18
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: kerbal
  name: openmct
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    name: openmct
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openmct
  namespace: kerbal
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: openmct.mytools.live
    http:
      paths:
      - path: /
        backend:
          serviceName: openmct
          servicePort: http
